version: '2'
services:
    mail:
        image: mailhog/mailhog
        ports:
        - 1080:8025
    submin:
        container_name: submin
        build: .
        # image: thaim/submin:0.3
        ports:
        - 80:80
        environment:
        - SUBMIN_HOSTNAME=localhost
        - SUBMIN_EXTERNAL_PORT=80
        - SUBMIN_SMTP_HOSTNAME=mail
        - SUBMIN_SMTP_PORT=1025
        - SUBMIN_ADMIN_MAIL=root@localhost
        volumes:
        - "$PWD/svn/old:/var/lib/svn-old"
        - "$PWD/svn/repos:/var/lib/svn"
        - "$PWD/config:/var/lib/submin"
        links:
        - mail
